### ISSUE TITLE
SASL Authentication

### ISSUE THREAD

**Issue by Akash-Mair** [streamthoughts/jikkou#167]
Hey!

New to Kafka and Jikkou - wondering how I can pass username and password credentials through. 
Using the latest docker image and trying in a docker compose.

My initial thought was to pass the file in via `--command-config` but keep hitting the timeout. My current `config.conf` looks like:

```
bootstrap.servers="<SERVER>"
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config="org.apache.kafka.common.security.scram.ScramLoginModule required username='<USERNAME>' password='<PASSWORD>';"
```

docker compose:
```
version: '3.7'
services:
  jikkou:
    image: streamthoughts/jikkou:latest
    env_file:
      - .env
    volumes:
      - ./config.conf:$HOME/.jikkou/config.conf
    command: --command-config=$HOME/.jikkou/config.conf brokers describe
    environment:
      - JIKKOU_DEFAULT_KAFKA_BOOTSTRAP_SERVERS:${ADDR}
```
