### ISSUE TITLE
ACL not being deleted with jikkou apply

### ISSUE THREAD

**Issue by dani** [streamthoughts/jikkou#194]
**Provide details of the setup you're running**
Running jikkou 0.20.0 in a Docker container, to manage a 3 broker Kafka cluster (Kafka 3.4.0), all of this being managed by Nomad. Jikkou is used to create/configure topics, and handle ACL

**Outline your question**
In previous Jikkou versions, I was able to use something like
```
/opt/jikkou/bin/jikkou \
  --bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS} \
  --command-config=/local/jikkou.properties \
  acls \
  apply \
  --files=/local/kafka-acls.yml \
  --delete-orphans \
  --yes \
  --include='.*'
  ```
which was exactly doing what I wanted: create/update ACL defined in /local/kafka-acls.yml, and remove any ACL existing on the cluster, but not defined in /local/kafka-acls.yml.

But with the new Jikkou version, I can't find how to do the same. I tried with
```
jikkou apply \
  --selector="kind IN (KafkaPrincipalRole,KafkaPrincipalAuthorization)" \
  --files=/local/kafka-acls.yml
```

With kafka-acls.yml using the new format, eg
```
---
apiVersion: kafka.jikkou.io/v1beta2
kind: KafkaPrincipalAuthorization
metadata:
  name: 'User:exchange-connect'
spec:
  roles:
    - main-producer
  acls:
    - type: ALLOW
      operations: [READ, WRITE, DESCRIBE, DESCRIBE_CONFIGS]
      resource:
        type: TOPIC
        pattern: __connect_
        patternType: PREFIXED
      host: '*'

    - type: ALLOW
      operations: [READ]
      resource:
        type: GROUP
        pattern: connect-exchange
        patternType: LITERAL
      host: '*'
```

It looks like it's creating/updating ACL defined here. But it's not removing ACL existing on the cluster and not defined in my yml. What am I missing ?

**Comment by fhussonnois** [comment]
Hi @dani, the new version of Jikkou introduces some changes in the way reconciliation is excuted. Previously, the absence of a resource description was interpreted as "deletion". Unfortunately, this was a dangerous approach that may lead to unwanted changes.

Now, to delete a resource, it must be explicitly annotated using : 

```yaml
---
apiVersion: kafka.jikkou.io/v1beta2
kind: KafkaPrincipalAuthorization
metadata:
  name: 'User:exchange-connect'
  annotations :
      jikkou.io/delete : true
spec:
```

Using such annotation will delete all ACL bindings for the principal `'User:exchange-connect'`. So, if for example you define ACLs for two principal `Alice` and `Bob` and just remove ACLs definition for `Alice` this will not remove ACLs from the cluster. 

However, if an ACL binding exists on the cluster for a principal defined in your resource definition file and this ACL binding is defined it will be deleted.

In any case, I'll be checking the problems and improving the tests on this part to make sure I haven't missed anything.
