### ISSUE TITLE
Group ACLs being ignored?

### ISSUE THREAD

**Issue by chrisoberle** [streamthoughts/jikkou#210]
I'm using jikkou on a mac w/ iam auth over MSK.  Auth works fine..however, with the resource below, jikkou does not great the acl for the group permission, only the topic.    

```
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalAuthorization"
metadata:
  name: "User:roger8"
spec:
  acls:
    - resource:
        type: TOPIC
        pattern: 'test-topic-1'
        patternType: 'MATCH'
      type: "ALLOW"
      operations: [ 'READ', 'WRITE' ]
      host: "*"

    - resource:
        type: GROUP
        pattern: '*'
        patternType: 'MATCH'
      type: "ALLOW"
      operations: [READ]
      host: "*"
``` 
Is there something wrong with my markup?  Heres the output from my --dry-run:

TASK [NONE] Unchanged ACL to ALLOW 'User:roger8' to execute operation(s) 'READ' on resource(s) 'TOPIC:LITERAL:test-topic-1' - OK
{
  "changed" : false,
  "end" : 1686079707748,
  "resource" : {
    "resourcePattern" : "test-topic-1",
    "patternType" : "LITERAL",
    "resourceType" : "TOPIC",
    "operation" : "READ",
    "type" : "ALLOW",
    "host" : "*",
    "principal" : "User:roger8",
    "operation" : "NONE"
  },
  "failed" : false,
  "status" : "OK"
}
TASK [NONE] Unchanged ACL to ALLOW 'User:roger8' to execute operation(s) 'WRITE' on resource(s) 'TOPIC:LITERAL:test-topic-1' - OK
{
  "changed" : false,
  "end" : 1686079707748,
  "resource" : {
    "resourcePattern" : "test-topic-1",
    "patternType" : "LITERAL",
    "resourceType" : "TOPIC",
    "operation" : "WRITE",
    "type" : "ALLOW",
    "host" : "*",
    "principal" : "User:roger8",
    "operation" : "NONE"
  },
  "failed" : false,
  "status" : "OK"
}
EXECUTION in 2s 500ms (DRY_RUN)
ok : 2, created : 0, altered : 0, deleted : 0 failed : 0
