### ISSUE TITLE
Feature: same syntaxe for user ACLs and role ACLs

### ISSUE THREAD

**Issue by gquintana** [streamthoughts/jikkou#29]
User ACLs are declared like this:
```
    - principal: 'User:myuser'
      roles: []
      permissions:
        - resource:
            type: topic
            pattern: mytopic
            pattern_type: PREFIXED
          allow_operations: ['READ:*', 'WRITE:*']
```
While the role permission are defined like this:
```
    - name: myrole
      resource:
        type: topic
        pattern: mytopic
        pattern_type: LITERAL
      allow_operations: ['READ:*', 'WRITE:*']
```
So a role is basically an alias for a single ACL.

What about having the same structure as users and be able to put multiple permissions in a role?
```
    - name: myrole
      permissions:
        - resource:
            type: topic
            pattern: mytopic
            pattern_type: PREFIXED
          allow_operations: ['READ:*', 'WRITE:*']
```
The role would be a group of users having the same permissions
