### ISSUE TITLE
KafkaAclChangeList output with duplicate keys

### ISSUE THREAD

**Issue by eigakow** [streamthoughts/jikkou#300]
**Describe the bug**
Running a jikkou diff, you get an output with a duplicate key OPERATION. This makes the yaml and json outputs difficult to post process.
 
**To Reproduce**
```
# jikkou diff -f myfile 
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaAclChangeList"
items:
- change:
    resourcePattern: "pattern1"
    patternType: "PREFIXED"
    resourceType: "GROUP"
    operation: "READ"
    type: "ALLOW"
    host: "*"
    principal: "User:Alice"
    operation: "DELETE"
- change:
    resourcePattern: "pattern2"
    patternType: "PREFIXED"
    resourceType: "GROUP"
    operation: "DESCRIBE"
    type: "ALLOW"
    host: "*"
    principal: "User:Bob"
    operation: "DELETE"
```
**Expected behavior**
An output should be in a valid yaml/json format without duplicate keys

**Runtime environment**
 - Jikkou: 0.29.0
