### ISSUE TITLE
ACL ordering

### ISSUE THREAD

**Issue by chrisoberle** [streamthoughts/jikkou#310]
**Search for existing answers**
Many questions have been asked before. Please have a quick search to see if there is already an answer to your question. There are two main resources for finding answers:

1. [Existing Jikkou Github issues, including _closed_ issues](https://github.com/streamthoughts/jikkou/issues?q=is%3Aissue)

If you can't see an answer to your question, then please raise a new Github or Stack overflow issue.

**Provide details of the setup you're running**
Using native image v0.29.0

**Outline your question**
I'm attempting to implement some roles that will grant read access to all topics matching a pattern but then deny access to a set of topics matching a different pattern.    My expectation was that the final state would respect the ordering of the declared roles and only apply the required changes.

Here's an example of what i'm attempting.  I'm wondering if this approach is reasonable or if i should be looking at some other strategy.

Is order respected in Role declarations?   Do "overrides" declared within an ACL take precedent over ACLs from Roles?

Thank you!

```
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalRole"
metadata:
  name: "PublicRead"
spec:
  acls:
    - resource:
        type: 'TOPIC'
        pattern: '.*(?<!\.private)$' # match everything not ending in private
        patternType: 'MATCH'
      type: "ALLOW"
      operations: [ 'READ', 'DESCRIBE' ]
      host: '*'
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalRole"
metadata:
  name: "DenyFoo"
spec:
  acls:
    - resource:
        type: 'TOPIC'
        pattern: '^Foo.*' # match everything starting with Foo
        patternType: 'MATCH'
      type: "DENY"
      operations: [ 'ALL' ]
      host: '*'
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalAuthorization"
metadata:
  name: "User:canary"
spec:
  roles:
    - PublicRead
    - DenyFoo
  acls:
    - resource:
        type: 'TOPIC'
        pattern: 'dev.canary'
        patternType: 'LITERAL'
      type: 'ALLOW'
      operations:  # Basically all permissions, except Delete.
        - 'READ'
        - 'WRITE'
        - 'CREATE'
        - 'ALTER'
        - 'ALTER_CONFIGS'
        - 'DESCRIBE'
        - 'DESCRIBE_CONFIGS'
      host: '*'
    - resource:
        type: 'GROUP'
        pattern: '*'
        patternType: 'LITERAL'
      type: 'ALLOW'
      operations:
        - 'READ'
        - 'DESCRIBE'
      host: '*'
```
