### ISSUE TITLE
I encountered a java.lang.NullPointerException when attempting to apply Kafka connector properties to an existing connector.

### ISSUE THREAD

**Issue by ajolakoskiMyne** [streamthoughts/jikkou#320]
**Describe the bug**
I encountered a java.lang.NullPointerException when attempting to apply Kafka connector properties to an existing connector. When i first apply  `jikkou apply -f kafkaconnect.yaml` it works great. If you run again it will throw error.

**To Reproduce**

1. Create kafka connect yaml
2. jikkou apply -f kafkaconnect.yaml
3. try again jikkou apply -f kafkaconnect.yaml 

**Expected behavior**
Normal response that will not fail gitlab CI/CD pipeline

**Screenshots/Configs**
![Screenshot from 2023-11-08 11-49-20](https://github.com/streamthoughts/jikkou/assets/150235541/58a95976-2ed9-4337-8363-db632e432c40)

**Runtime environment**
 - OS: Ubuntu
 - Jikkou: 0.30.0

**Comment by fhussonnois** [comment]
Hi @ajolakoskiMyne, thank you for reporting this issue. I figured out the problem. It will be fixed in the next version. In the meantime, you can solve the problem by adding the `spec.state` field to your YAML file as follows: 

```yaml
---
---
apiVersion: "kafka.jikkou.io/v1beta1"
kind: "KafkaConnector"
metadata:
  name: ...
  labels:
    kafka.jikkou.io/connect-cluster: ...
spec:
  # Name or alias of the class for this connector.
  connectorClass: ...
  tasksMax: ...
  config:
    ....
  # --> The state the connector should be in [running, stopped, paused]. Defaults to running.
  state: "RUNNING"
```

```
