### ISSUE TITLE
Feature: apply changes following plan order

### ISSUE THREAD

**Issue by gquintana** [streamthoughts/jikkou#37]
When running 
```
  topics:
    - name: topic1
      partitions: 3
      replication_factor: 2
    - name: topic2
      partitions: 3
      replication_factor: 2
```
The output is 
```
TASK [CREATE] Create a new topic topic2 (partitions=3, replicas=2) - OK ****************************
TASK [CREATE] Create a new topic topic1 (partitions=3, replicas=2) - OK ****************************
```
Topics are created following a random order, it makes it hard 
* to check what's being done (or about to be done when dry run mode)
* to debug the plan content

I'd like the plan ordered to be respected
