### ISSUE TITLE
add support for specifying common config props shared between multipe topics

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/jikkou#40]
The idea is to be able to specify something like : 

```yaml
version: 1
metadata: {}
specs:
  config_maps:
    - name: "DefaultCleanupPolicy"
      configs:
        cleanup.policy: delete
        retention.ms: 10000

  topics:
    - name: 'my-topic-p1'
      partitions: 1
      replication_factor: 1
      config_map_refs: [DefaultCleanupPolicy]

    - name: 'my-topic-p2'
      partitions: 2
      replication_factor: 1
      config_map_refs: [DefaultCleanupPolicy]
```
