### ISSUE TITLE
Dynamically connect to a kafka-connect cluster

### ISSUE THREAD

**Issue by arnoldyahad** [streamthoughts/jikkou#416]
Hello, 
I want to use Jikkou to manage kafka-connectors and I have multiple kafka-connect deployment throughout my organization.
We would like to consider the option to run 1 deployment for Jikkou to manage all our kafka-connect connectors.

The issue we have is that we would like to be able dynamically control ` KafkaConnector`  resources and not be depended on the Jikkou connect configuration in-order to deploy a configuration.

Current Situation: 
our connector references the connect-cluster:
```
apiVersion: "kafka.jikkou.io/v1beta1"
kind: "KafkaConnector"
metadata:
  name: "s3-sink"
  labels:
    kafka.jikkou.io/connect-cluster: "my-connect-cluster"
```

and the connect cluster is configured in the connect extention configuration:
```
jikkou {
  extensions.provider.kafkaconnect.enabled = true
  kafkaConnect {
    clusters = [
      {
        name = "my-connect-cluster"
        url = "http://localhost:8083"
      }
    ]
  }
}
```

I would like the ability to not update the `clusters` for each kafkaConnect we have  and control the `kafka.jikkou.io/connect-cluster` directly. 

for example reference the cluster through the kubernetes service:
```
apiVersion: "kafka.jikkou.io/v1beta1"
kind: "KafkaConnector"
metadata:
  name: "s3-sink"
  labels:
    kafka.jikkou.io/connect-cluster: "kafka-connect-sink:8083"
```

or directly through ip:
```
apiVersion: "kafka.jikkou.io/v1beta1"
kind: "KafkaConnector"
metadata:
  name: "s3-sink"
  labels:
    kafka.jikkou.io/connect-cluster: "1.2.3.4:8083"
```

this will allow us to use KafkaConnector resources freely without being related on the connect configuratoin and without having conflicts (When multiple devs will try to edit the deployment, or when this list becomes too big to maintain).
