### ISSUE TITLE
jikkou get kt returns the same topic id for all topics

### ISSUE THREAD

**Issue by sandile-yakka** [streamthoughts/jikkou#424]
Hi, I have an issue where fetching a list of already existing topics from kafka 2.1.1 using jikkou v0.33.3 returns a list of topics all of which have the same topic ID.  Should this be a point of concern? I worry that changing the configuration of one of the topics might result in an inadvertent change in the others.

```
jikkou get kt 

apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: "<redacted>"
  labels:
    kafka.jikkou.io/topic-id: "AAAAAAAAAAAAAAAAAAAAAA"
  annotations:
    kafka.jikkou.io/cluster-id: "mFMXM7FcRhSVImM2mO0-JA"
    jikkou.io/generated: "2024-04-18T12:45:22.900088Z"
spec:
  partitions: 6
  replicas: 2
  configs:
    retention.ms: "345600000"
  configMapRefs: []
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: "<redacted>"
  labels:
    kafka.jikkou.io/topic-id: "AAAAAAAAAAAAAAAAAAAAAA"
  annotations:
    kafka.jikkou.io/cluster-id: "mFMXM7FcRhSVImM2mO0-JA"
    jikkou.io/generated: "2024-04-18T12:45:22.900088Z"
spec:
  partitions: 3
  replicas: 2
  configs:
    retention.ms: "345600000"
  configMapRefs: []
```
