### ISSUE TITLE
Native build does not support PyList or PyMap methods

### ISSUE THREAD

**Issue by dav-garcia** [streamthoughts/jikkou#426]
**Describe the bug**
The native build (at least when run from the public Docker image) fails when the template invokes any of the public methods of PyList (append, insert, etc.) or PyMap (update, items, etc.).

**To Reproduce**
Template:
```
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: test
  labels:
    {% set d = {} %}
    {% do d.update({'a': 1}) %}
    {{ d | toyaml }}
spec:
```

Command:
```
docker run -it \
        --volume $HOME/.jikkou:/etc/jikkou --volume ./templates:/opt/templates \
        --user $(id -u) --rm streamthoughts/jikkou:0.33.3 prepare -f /opt/templates/test.yaml
```

Result:
```
Error: JikkouRuntimeException: Cannot render resource template. 'SyntaxError': line 7, start_pos: -1, Cannot find method update with 1 parameters in class com.hubspot.jinjava.objects.collections.SizeLimitingPyMap
```

Note: Jikkou config not provided as it is irrelevant.

**Expected behavior**
Running from the JAR:
```
java -jar jikkou-cli-0.33.3-runner.jar prepare -f templates/test.yaml
```

Result:
```
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: "test"
  labels:
    a: 1
  annotations:
    jikkou.io/managed-by-location: "test.yaml"
```

**Screenshots/Configs**
N/A

**Runtime environment**
 - OS: Ubuntu 22.04
 - Jikkou: 0.33.3
 - Docker version: 26.1.0
 - Kafka Cluster Version: 3.7.0

**Additional context**
N/A
