### ISSUE TITLE
Support for dot-separated properties in values files

### ISSUE THREAD

**Issue by dav-garcia** [streamthoughts/jikkou#437]
**Is your feature request related to a problem? Please describe.**
My KafkaTopic resources use default config properties from a values file like this:
```
topics:
  defaults:
    partitions: 6
    replicas: 3
    configs:
      retention.ms: 2419200000 # 28 days
```
Applying those values in the template with the `toyaml` filter results in a YAML resource with the dot-separated properties split like this:
```
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  ...
spec:
  partitions: 6
  replicas: 3
  configs:
    retention:
      ms: 2419200000
```
And then, the tool fails with this error:
```
|  #1 | TopicConfigKeysValidation | Config key 'retention' for topic    | {}      |
|     |                           | '...' is not valid                  |         |
```

For reference, here's the code in the template:
```
...
{% set defaults = values.topics.defaults %}
...
spec:
  partitions: {{ customizations.partitions | default(defaults.partitions) }}
  replicas: {{ customizations.replicas | default(defaults.replicas) }}
  configs:
    {% set configs = {} %}
    {% do configs.update(defaults.configs) %}
    {% do configs.update(customizations.configs) %}
    {{ configs | toyaml | indent(4) }}
```

**Describe the solution you'd like**
Honestly, I am quite surprised no one has faced this problem. Either I'm doing something wrong or my use case isn't that common (FWIW, we are moving from an imperfect but working Helm chart with Julie).

So, my request is to either:
a) Don't split YAML keys in values files.
b) Dot-join the nested config properties under `configs` in the `KafkaTopic` resource before actually validating and applying them.
c) Enable recursive macro support in JinJava (I've defined a recursive macro to "flatten" the nested maps but recursion is disabled):
`JinjavaConfig.newBuilder().withEnableRecursiveMacroCalls(true)...`

**Describe alternatives you've considered**
As I said above, maybe my template is wrong. If so, any advice is greatly appreciated.

**Additional context**
Thanks very much.
