### ISSUE TITLE
ACLs deletion not working on AIVEN

### ISSUE THREAD

**Issue by bertrandcedric** [streamthoughts/jikkou#468]
**Describe the bug**
I got the following erreur when I try to delete an ACL TOPIC in AIVEN KAFKA :
`
NullPointerException: Cannot invoke "io.streamthoughts.jikkou.extension.aiven.api.data.KafkaAclEntry.id()" because the return value of "io.streamthoughts.jikkou.extension.aiven.change.acl.KafkaAclEntryChangeHandler$Delete.getEntry(io.streamthoughts.jikkou.core.models.change.ResourceChange, java.lang.Class)" is null
`

**To Reproduce**

The sample yaml resource to delete the ACL :

```yaml
---
apiVersion: "kafka.aiven.io/v1beta1"
kind: "KafkaTopicAclEntryList"
items:
  - metadata:
      annotations:
        jikkou.io/delete: true
    spec:
      permission: "READWRITE"
      username: "test"
      topic: "test"
```

**Expected behavior**
We expect that the ACLs is delete in AIVEN.

**Runtime environment**
 - Jikkou: 0.33.3 / 0.34.0
 - Kafka Cluster Version: AIVEN 3.6.2
