### ISSUE TITLE
Cannot Delete Keys from Existing Connectors

### ISSUE THREAD

**Issue by aaronmillerbraze** [streamthoughts/jikkou#483]
**Describe the bug**
When trying to remove configuration keys from an existing connector, it throws a NullPointerException

**To Reproduce**
Have an existing/deployed Connector, then remove a configuration key:

``` yaml
---
connectorName: "example-connector"
tasksMax: "1"
connectClusterName: "example-connect-cluster"
connectorClassName: "io.confluent.connect.http.HttpSinkConnector"
config:
  confluent.topic.bootstrap.servers: "{{ values.bootstrap.servers }}"
  reporter.bootstrap.servers: "{{ values.bootstrap.servers }}"
  http.api.url: "http://localhost" # REMOVE THIS CONFIGURATION LINE
  topics: "example-topic"
state: "RUNNING"
```

this then becomes:

``` yaml
---
connectorName: "example-connector"
tasksMax: "1"
connectClusterName: "example-connect-cluster"
connectorClassName: "io.confluent.connect.http.HttpSinkConnector"
config:
  confluent.topic.bootstrap.servers: "localhost:9092"
  reporter.bootstrap.servers: "localhost:9092"
  topics: "example-topic"
state: "RUNNING"
```

then run `jikkou update`, and we get:

``` formatted
TASK [UPDATE] Update connector 'example-connector' on Kafka Connect cluster 'example-connect-cluster' - FAILED
{
  "end" : "2024-08-14T20:19:10.350440Z",
  "status" : "FAILED",
  "description" : "Update connector 'example-connector' on Kafka Connect cluster 'example-connect-cluster'",
  "errors" : [ {
    "message" : "NullPointerException: null"
  } ],
  "changed" : false,
  "failed" : true,
  "change" : {
    "apiVersion" : "kafka.jikkou.io/v1beta1",
    "kind" : "KafkaConnectorChange",
    "metadata" : {
      "name" : "example-connector",
      "labels" : {
        "kafka.jikkou.io/connect-cluster" : "example-connect-cluster"
      },
      "annotations" : {
        "jikkou.io/managed-by-location" : "templates/kafka-connect-template.tpl"
      }
    },
    "spec" : {
      "changes" : [ {
        "name" : "connectorClass",
        "op" : "NONE",
        "before" : "io.confluent.connect.http.HttpSinkConnector",
        "after" : "io.confluent.connect.http.HttpSinkConnector"
      }, {
        "name" : "tasksMax",
        "op" : "NONE",
        "before" : 1,
        "after" : 1
      }, {
        "name" : "state",
        "op" : "NONE",
        "before" : "RUNNING",
        "after" : "RUNNING"
      }, {
        "name" : "config.topics",
        "op" : "NONE",
        "before" : "example-topic",
        "after" : "example-topic"
      }, {
        "name" : "config.reporter.bootstrap.servers",
        "op" : "NONE",
        "before" : "localhost:9092",
        "after" : "localhost:9092"
      }, {
        "name" : "config.confluent.topic.bootstrap.servers",
        "op" : "NONE",
        "before" : "localhost:9092",
        "after" : "localhost:9092"
      }, {
        "name" : "config.http.api.url",
        "op" : "DELETE",
        "before" : "http://localhost"
      } ],
      "op" : "UPDATE",
      "data" : { }
    }
  }
}
```

**Expected behavior**
The connector configuration should be updated with the specific configuration line removed.

**Screenshots/Configs**

**Runtime environment**
 - OS: macOS Sonoma 14.1.1
 - Jikkou: 0.35.0
 - Docker version: N/A (can reproduce using Java executable)
 - Kafka Cluster Version: CP 7.5.3

**Additional context**
For context, the YAML code above gets fed into a standard Kafka Connector template that we've defined here:

``` formatted
---
apiVersion: "kafka.jikkou.io/v1beta1"
kind: "KafkaConnector"
metadata:
  name: {{ values.connectorName }}
  labels:
    kafka.jikkou.io/connect-cluster: {{ values.connectClusterName }}
spec:
  connectorClass: {{ values.connectorClassName }}
  tasksMax: {{ values.tasksMax }}
  config:
  {% for config in values.config|split("\n") %}
    {{ config }}
  {% endfor %}
  state: "{{ values.state | default('RUNNING') }}"
```

**PS**
This is an incredible tool. Thank you so much @fhussonnois!
