### ISSUE TITLE
Include trace from Failed Connector Tasks

### ISSUE THREAD

**Issue by aaronmillerbraze** [streamthoughts/jikkou#486]
**Is your feature request related to a problem? Please describe.**

Currently when connector tasks are failing, the only way to get trace information from the Kafka Connect cluster is to make an HTTP request to the Kafka Connect REST API at this endpoint: http://<kafka-connect-cluster-name>:8083/connectors?expand=status&expand=info

By running `jikkou get kafkaconnectors --expand-status`, the tool already grabs some of the task information such as the `id`, `state`, and `workerId`, but it does not include the `trace` information (if a task has failed). Here is an example of a failed connector task with trace information from the Kafka Connect REST API:

``` json
{
  "example-connector": {
    "status": {
      "name": "example-connector",
      "connector": {
        "state": "RUNNING",
        "worker_id": "<redacted>:8083"
      },
      "tasks": [
        {
          "id": 0,
          "state": "FAILED",
          "worker_id": "<redacted>:8083",
          "trace": "org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:223)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:149)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic example-topic to Avro: \n\tat io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:124)\n\tat org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:88)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)\n\t... 13 more\nCaused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!\n\tat io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.getByteBuffer(AbstractKafkaSchemaSerDe.java:244)\n\tat io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer$DeserializationContext.<init>(AbstractKafkaAvroDeserializer.java:334)\n\tat io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:202)\n\tat io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:172)\n\tat io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:107)\n\t... 17 more\n"
        }
      ],
      "type": "sink"
    },
    "info": {
      "name": "example-connector",
      "config": {
        "connector.class": "io.confluent.connect.http.HttpSinkConnector",
        "confluent.topic.bootstrap.servers": "localhost:9092",
        "tasks.max": "1",
        "topics": "example-topic",
        "http.api.url": "http://localhost",
        "name": "example-connector",
        "reporter.bootstrap.servers": "localhost:9092"
      },
      "tasks": [
        {
          "connector": "example-connector",
          "task": 0
        }
      ],
      "type": "sink"
    }
  }
}
```

and here is what Jikkou returns when running `jikkou get kafkaconnectors --expand-status`:

``` yaml
---
apiVersion: "kafka.jikkou.io/v1beta1"
kind: "KafkaConnector"
metadata:
  name: "example-connector"
  labels:
    kafka.jikkou.io/connect-cluster: "example-connect-cluster"
  annotations:
    jikkou.io/generated: "2024-08-20T19:13:26.206404Z"
spec:
  connectorClass: "io.confluent.connect.http.HttpSinkConnector"
  tasksMax: 1
  config:
    confluent.topic.bootstrap.servers: "localhost:9092"
    topics: "example-topic"
    http.api.url: "http://localhost"
    reporter.bootstrap.servers: "localhost:9092"
  state: "RUNNING"
status:
  connectorStatus:
    name: "example-connector"
    connector:
      state: "RUNNING"
      workerId: "<redacted>:8083"
    tasks:
    - id: 0
      state: "FAILED"
      workerId: "<redacted>:8083"
```

**Describe the solution you'd like**

If trace information for a failed task could be included as part of the results from running `jikkou get kafkaconnectors --expand-status`, this would eliminate the extra hop of making another HTTP call to the Kafka Connect REST API just to get trace info.

**Describe alternatives you've considered**
As mentioned above, we would need to issue an HTTP request to the Kafka Connect REST API to get trace info for a failed connector task.

**Additional context**
I'm currently using Jikkou 0.35.2 on macOS Sonoma 14.1.1
