### ISSUE TITLE
Create a new provider with a resource kind to manage Role Bindings (RBAC) for Confluent Cloud 

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/jikkou#491]
**Is your feature request related to a problem? Please describe.**
Jikkou should offer a dedicated provider for Confluent Cloud to manage role bindings.

**Describe the solution you'd like**
Create a new provider to manage a new `RoleBinding` resource: 
```
apiVersion: "iam.confluent.cloud/v1
kind: "RoleBinding"
metadata: {}
spec:
   # The principal User to bind the role to
   principal: <string(^User:.+$)>
   # The name of the role to bind to the principal
   roleName: <string>
   # A CRN that specifies the scope and resource patterns necessary for the role to bind
   crnPattern: <string <uri> ^crn://.+$>
```

Note: For that resource we could use the same schema that the one of the official terraform provider.
see: https://docs.confluent.io/cloud/current/api.html#tag/Role-Bindings-(iamv2)/The-Role-Bindings-Model

The 3 properties: `principal`, `roleName`, and `crnPattern` should be used as an Identifier to detect changes.

This new provider should be more or less similar to the one Jikkou already provides for Aiven: https://github.com/streamthoughts/jikkou/tree/main/providers/jikkou-provider-aiven
