### ISSUE TITLE
JsonMappingException: Cannot apply a file containing different resources 

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/jikkou#493]
**Describe the bug**

```
Error: JikkouRuntimeException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.streamthoughts.jikkou.core.reconciler.DefaultChangeResult["description"])
```

**To Reproduce**

```java
jikkou apply --dry-run -f ./resource.yaml
```

```
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaPrincipalAuthorization
metadata:
  name: 'User:test'
spec:
  acls:
    - resource:
        type: 'topic'
        pattern: '*'
        patternType: 'LITERAL'
      type: 'ALLOW'
      operations: ['ALL']
      host: '*'
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaTopicList
items:
  - metadata:
      name: 'testtopic'
    spec:
      partitions: 10
      replicas: 3
```

**Expected behavior**

**Screenshots/Configs**

**Runtime environment**
 - OS: [e.g. Ubuntu]
 - Jikkou: 0.35.2
 - Docker version: [e.g. 18.03.1-ce]
 - Kafka Cluster Version: [e.g. 2.8.1, cp-6.0.0]

**Additional context**
