### ISSUE TITLE
ACLs generation using template available ?

### ISSUE THREAD

**Issue by Antoine7773** [streamthoughts/jikkou#496]
**Provide details of the setup you're running**
Ubuntu 20.04.6
Docker version 26.1.4
Jikkou v0.35.3

Comamnd executed:
`docker run -it --net host --mount type=bind,source=$HOME/jikkouconfig,target=/etc/jikkou/config --mount type=bind,source=/<source_path>,target=/etc/default_templates_suggestion/ streamthoughts/jikkou:latest prepare --files /etc/default_templates_suggestion/acls/template_files/template.tpl --values-files /etc/default_templates_suggestion/acls/values_files/values.yaml`

Template used _template.tpl_ :
```
 apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalAuthorizationList"
items:
{% for user, topics in values.users.items() %}
- metadata:
    name: "User:{{ user }}"
  spec:
    acls:
    {% for topic, ops in topics.items() %}
      - resource:
          type: 'topic'
          pattern: '{{ topic }}'
          patternType: 'LITERAL'
        type: "ALLOW"
        operations: 
        {% for op in ops %}
          - {{ op }}
        {% endfor %}
        host: "*"
    {% endfor %}
{% endfor %}
```

Values file used _values.yaml_:
```
users:
  user1:
    cluster.topicA: 
      - 'READ'
      - 'WRITE'
    cluster.topicB: 
      - 'READ'
  user2:
    cluster.topicC: 
      - 'READ'
  user3:
    cluster.topicD: 
      - 'READ'
```
      
But the output is :
```
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalAuthorizationList"
metadata:
  labels: {}
  annotations:
    jikkou.io/managed-by-location: "/etc/default_templates_suggestion/acls/template_files/template.tpl"
```

I would have expected something like :
```
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalAuthorizationList"
items:
- metadata:
    name: "User:user1"
  spec:
    acls:
      - resource:
          type: 'topic'
          pattern: 'forexca.topicA'
          patternType: 'LITERAL'
        type: "ALLOW"
        operations:
          - READ
          - WRITE
        host: "*"
      - resource:
          type: 'topic'
          pattern: 'forexca.topicB'
          patternType: 'LITERAL'
        type: "ALLOW"
        operations:
          - READ
        host: "*"
- metadata:
    name: "User:user2"
  spec:
    acls:
      - resource:
          type: 'topic'
          pattern: 'forexca.topicC'
.
.
.
```

**Outline your question**
Do you know if we can generate ACLs using template with jikkou or if it is only available for topics creation ?
(Tried the template with python and it is giving expected output)
