### ISSUE TITLE
Conflicting property-based creators during upgrade to v0.35.4

### ISSUE THREAD

**Issue by RouxAntoine** [streamthoughts/jikkou#513]
Hello

**Describe the bug**

After upgrading from v0.33.3 to v0.35.4, we have an error to on aiven acl topic resources.

**To Reproduce**

input testing resources that we use

```
---
apiVersion: "kafka.aiven.io/v1beta1"
kind: "KafkaTopicAclEntry"
metadata:
  annotations:
    decathlon.com/domain: "address"
spec:
  username: bob
  permission: READWRITE
  topic: '*'
---
apiVersion: "kafka.aiven.io/v1beta1"
kind: "KafkaTopicAclEntry"
metadata:
  annotations:
    decathlon.com/domain: "address"
spec:
  username: alice
  permission: READWRITE
  topic: '*alice*'
---
apiVersion: "kafka.aiven.io/v1beta1"
kind: "KafkaTopicAclEntry"
metadata:
  annotations:
    decathlon.com/domain: "streaming"
spec:
  username: member-sport
  permission: READ
  topic: 'local.dkt-member.streaming.public.fact.demo-member-event.v1.avro'
```

Sorry for the bad reproducer as you know (For @fhussonnois) this is a little complex to give a reproducer code in our case.

**Expected behavior**

As of before no change in the jikkou log output because we do not change the input acl resources.

**Screenshots/Configs**

here is the stack trace

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already 
had explicit creator [constructor for `io.streamthoughts.jikkou.core.models.change.SpecificStateChange` (4 args), 
annotations: {interface java.beans.ConstructorProperties=@java.beans.ConstructorProperties({"name", "op", "before", 
"after", "description"})}, encountered another: [constructor for 
`io.streamthoughts.jikkou.core.models.change.SpecificStateChange` (5 args), annotations: {interface 
java.beans.ConstructorProperties=@java.beans.ConstructorProperties({"name", "op", "before", "after", "description"})} 
(through reference chain: io.streamthoughts.jikkou.kafka.reporter.ce.CloudEventEntity["data"]-
>io.streamthoughts.jikkou.core.reconciler.DefaultChangeResult["change"]-
>io.streamthoughts.jikkou.core.models.change.GenericResourceChange["spec"]-
>io.streamthoughts.jikkou.core.models.change.GenericResourceChangeSpec["changes"]-
>java.util.Collections$UnmodifiableList[0])
```

**Additional context**

My supposition is a conflict between

https://github.com/streamthoughts/jikkou/blob/main/core/src/main/java/io/streamthoughts/jikkou/core/models/change/SpecificStateChange.java#L32

and

https://github.com/streamthoughts/jikkou/blob/main/core/src/main/java/io/streamthoughts/jikkou/core/models/change/SpecificStateChange.java#L54

both have 

```
    @ConstructorProperties({
            "name",
            "op",
            "before",
            "after",
            "description"
    })
```

the first one should be instead

```
    @ConstructorProperties({
            "name",
            "op",
            "before",
            "after"
    })
```
