### ISSUE TITLE
Jikkou is unable to select inside a list.

### ISSUE THREAD

**Issue by omegaspard** [streamthoughts/jikkou#547]
**Describe the bug**
Jikkou is unable to select inside a list.

**To Reproduce**

For a yaml returned by a command such as:

./jikkou ka get

```
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaPrincipalAuthorization"
metadata:
  name: "User:my-user"
  labels: {}
  annotations:
    kafka.jikkou.io/cluster-id: "_my-cluster-id"
    jikkou.io/generated: "2025-03-11T11:45:12.191232Z"
spec:
  acls:
  - resource:
      type: "TOPIC"
      pattern: "my-topic"
      patternType: "LITERAL"
    operations:
    - "DESCRIBE"
    - "CREATE"
    - "WRITE"
    type: "ALLOW"
    host: "*"
  roles: []
```
I want to execute :

`./jikkou get kafkaprincipalauthorizations   --selector 'spec.acls[].resource.pattern MATCHES (my-topic)'`

**Expected behavior**
The goal is to return all the acl containing on the topic my-topic.
But I get the error `Error: SelectorException: Index 0 out of bounds for length 0`

**Screenshots/Configs**

![Image](https://github.com/user-attachments/assets/7cfc5f1b-335c-440e-b8dc-304c8de0ffe5)

**Runtime environment**
 - OS: Ubuntu 22.05.5 LTS
 - Jikkou: Jikkou version "0.35.7" 2025-01-31 JVM: 21.0.2 (GraalVM Community Substrate VM 21.0.2+13)
 - Kafka Cluster Version: 3.1.0 Confluent
