### ISSUE TITLE
Schema field order automatically rearranged

### ISSUE THREAD

**Issue by scanchon** [streamthoughts/jikkou#596]
**Describe the bug**
Jikkou does not preserve the schema field order

**To Reproduce**
Given the following `SchemaRegistryKind` configuration:
```
---
apiVersion: "schemaregistry.jikkou.io/v1beta2"
kind: "SchemaRegistrySubject"
metadata:
  name: "schema2"
  labels: {}
spec:
  schemaType: "JSON"
  schema: "{\"properties\":{\"b\":{\"type\":\"integer\"\
    },\"a\":{\"type\":\"integer\"}},\"description\":\"test schema\",\"title\":\"schema2\",\"type\":\"object\"}"
```

When we run the validate command (which generates the configuration that will also be utilized for the apply command), the output is:
```
$ jikkou validate -f b.yaml
---
apiVersion: "schemaregistry.jikkou.io/v1beta2"
kind: "SchemaRegistrySubject"
metadata:
  name: "schema2"
  labels: {}
  annotations:
    jikkou.io/managed-by-location: "b.yaml"
spec:
  schemaType: "JSON"
  schema: "{\"description\":\"test schema\",\"properties\":{\"a\":{\"type\":\"integer\"\
    },\"b\":{\"type\":\"integer\"}},\"title\":\"schema2\",\"type\":\"object\"}"
  references: []
```
All fields have now been arranged in alphabetical order, including those nested within properties. Consequently, the schema is registered with the properties in alphabetical order.

The issue arises when we attempt to obtain the schema ID from the source schema using [Confluent's Schema Registry API](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)). We encounter a 404 error because the source schema, which is unordered, does not match the registered schema, which has been ordered by Jikkou.

**Expected behavior**
If nothing is specified, the source schema ordering should be preserved

**Runtime environment**
 - Jikkou: 0.35.7
 - Confluent Schema registry 7.9.1
