### ISSUE TITLE
Support of type Transactional IDs in ACL resources?

### ISSUE THREAD

**Issue by vpoyraz** [streamthoughts/jikkou#71]
We are using jikkou (0.8.0) and wanted to know how we could apply ACLs for a transactional producer using the ACL resource. 

We would typically use the kafka admin tools to do this with the below:

```bash
kafka-acls --bootstrap-server localhost:9092 --command-config adminclient-configs.conf \
   --add --transactional-id * --allow-principal User:* --operation write
```

I haven't extensively tested jikkou so I cannot comment at this stage whether there are additional flags for this type of ACL, but would appreciate any light that is shed on this.

Cheers.

**Comment by fhussonnois** [comment]
Hi @vpoyraz,

I think ACLs on Transactional IDs is currently not supported. This feature will be added for the next release.

Cheers.

**Comment by fhussonnois** [comment]
Hi @vpoyraz,

Well, after checking you should be able to manage  ACLs for the transactional producer (using Jikkou 0.8.0à like this : 

```yaml
version: 1
specs:
  security:
    users:
    - principal : 'User:*'
      roles  : []
      permissions :
        - resource :
            type : 'transactional_id'
            pattern: '*'
            pattern_type : 'LITERAL'
          allow_operations : ['WRITE:*']
```
